layout_spectrum: 0.525659
typography_spectrum: 0.838038
color:
  saturation: 0.2429012
  lightness: 0.6051927
  brandStrength: 0.5910539
  rhythmicContrast: 0.7109705
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: "Kelvin's Memories"
