collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6469534
color:
  saturation: 1
  brandStrength: 0.6989247
  lightness: 0.9480287
  brandColors:
    - '#E2D7CD'
    - '#9AB3E0'
    - '#67636E'
    - '#F2A587'
    - '#0E040D'
  rhythmicContrast: 1
layout_spectrum: 1
name: Chez Kelvin
