collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.672043
  brandStrength: 0.5910539
  lightness: 0.2168459
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.8548387
typography_spectrum: 0.6469534
layout_spectrum: 0.525659
name: "Kelvin's Memories"
